gravity/main/routes.py
from unicodedata import name
from flask import Blueprint, flash, redirect, render_template, request, url_for, abort
from flask_login import current_user, login_required
from gravity import db
from gravity.database import Satelite, Plot
from gravity.main.forms import AddSateliteForm, GeneratePlotForm
from gravity.main.utils import save_trans_plot ,convert_to_list
from gravity.simulation.main import Body, Earth, plot_satelites

main = Blueprint('main', __name__)


@main.route("/home")
@main.route("/", methods=['GET', 'POST'])
def home():
    # Default plot
    plot_image = url_for('static', filename='orbit_plots/Example_orbit.png')

    # Formm to input satelites by pos and vel
    form = AddSateliteForm()
    if form.validate_on_submit():
        # logged in user adds satelites to database
        if current_user.is_authenticated:
            satelite = Satelite(name=form.name.data, pos_0=form.pos.data, vel_0=form.vel.data, user_id=current_user.id)
            db.session.add(satelite)
            db.session.commit()
            flash(f'Satelite added', 'success')
            return redirect(url_for('main.home'))
        # non user generates plot on subbmit
        else:
            pos = convert_to_list(form.pos.data)
            vel = convert_to_list(form.vel.data)
            sat = Body(pos, vel, central_body=Earth)
            p_path = plot_satelites([sat,], save=True, filename='temp')
            p_name = save_trans_plot(p_path, random=False)
            plot_image = url_for('static', filename='orbit_plots/' + p_name)

    plot_form = GeneratePlotForm()
    # get satelites owned by the user
    try:
        user_satelites = Satelite.query.filter_by(user_id=current_user.id)
    except:
        user_satelites = []

    # logged in user can generate all satelites and change view angle here
    if current_user.is_authenticated:
        if plot_form.validate_on_submit():
            # Formating: view angles
            v_angle = convert_to_list(plot_form.view_angles.data, target=2)
            # and satelites to plot
            sats = []
            for satelite in user_satelites:
                pos = convert_to_list(satelite.pos_0)
                vel = convert_to_list(satelite.vel_0)
                sats.append(Body(pos, vel, central_body=Earth))

            # Generate and save plot for the current user
            # plot_satelites automatically calcultes their paths
            p_path = plot_satelites(sats, view_angle=v_angle ,save=True, filename='temp')
            p_name = save_trans_plot(p_path, random=True)
            plot_image = url_for('static', filename='orbit_plots/' + p_name)
            # save to the database (TODO Is it actually needed?)
            plot = Plot(plot_image=plot_image, user_id=current_user.id)
            db.session.add(plot)
            db.session.commit()

    return render_template('home.html', form=form, plot_form=plot_form, 
                           user_satelites=user_satelites, plot_image=plot_image)


@main.route("/satelite/<int:satelite_id>/delete", methods=['POST'])
@login_required
def delete_satelite(satelite_id):
    satelite = Satelite.query.get_or_404(satelite_id)
    # .owner is a backref to the user data (lookup in database.py User)
    if satelite.owner != current_user:
        abort(403)
    db.session.delete(satelite)
    db.session.commit()
    flash('Satelite was deleted from the list!', 'success')

    return redirect(url_for('main.home'))




@main.route("/about")
def about():
    return render_template('about.html')

gravity/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from gravity import db
from gravity.database import User
from gravity.users.forms import (LoginForm, RegistrationForm, RequestResetForm,
                                 ResetPasswordForm, UpdateAccountForm)
from gravity.users.utils import save_picture, send_password_reset_email
from werkzeug.security import check_password_hash, generate_password_hash

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    # Ensure user is not logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    # request.form.get method is handled in forms.py by FlaskForm
    form = RegistrationForm()
    # user subbmits form via POST
    if form.validate_on_submit():
        password_hash = generate_password_hash(form.password.data)

        # Create user and add them to the database
        user = User(username=form.username.data, email=form.email.data, password=password_hash)
        db.session.add(user)
        db.session.commit()

        flash(f'Hello "{form.username.data}"! You have sucessfully created your account. Please login', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    # Ensure user is not logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    # request.form.get method is handled in forms.py by FlaskForm
    # user subbmits form via POST
    form = LoginForm()
    if form.validate_on_submit():
        # querry the database
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            # function from flask_login
            login_user(user, remember=form.remember.data)
            flash('You have been successfully logged in!', 'success')

            # Redirect user back to the page they tried to acces but were requred to login
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Username and/or Password do not match', 'danger')

    return render_template('login.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pictures/' + current_user.image_file)
    return render_template('account.html', form=form, image_file=image_file)


@users.route("/password_reset", methods=['GET', 'POST'])
def password_reset_request():
    # Ensure user is not logged in
    next_page = request.args.get('next')
    if current_user.is_authenticated and not next_page:
        return redirect(url_for('main.home'))

    # Sending password reset email
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_password_reset_email(user)
        flash('A password reset email has been sent. Check your inbox to reset password.', 'info')
        return redirect(url_for('users.login'))

    return render_template('password_reset.html', form=form)


@users.route("/password_reset/<token>", methods=['GET', 'POST'])
def password_reset_token(token):
    # Ensure user is not logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    # Ensure token is valid and non expired
    user = User.verify_reset_token(token)
    if user is None:
        flash('This request has expired or is invalid. Request password reset again.', 'warning')
        return redirect(url_for('users.password_reset_request'))
    
    # New password form and assigment
    form = ResetPasswordForm()
    if form.validate_on_submit():
        password_hash = generate_password_hash(form.password.data)
        user.password = password_hash
        db.session.commit()
        flash(f'Your password has been reset. Please login', 'success')
        return redirect(url_for('users.login'))

    return render_template('password_reset_token.html', form=form)

gravity/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock title %}

{% block main%}
    <h2>About Page</h2>
{% endblock main %}

gravity/templates/account.html
{% extends "layout.html" %}

{% block title %}
    Account
{% endblock title %}

{% block main%}
    <div class="media d-flex justify-content-md-start">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2>{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom border-dark mb-4">Account Information</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <div class="border-top border-dark pt-3">
        Request password change: <a class="ml-2" href="{{ url_for('users.password_reset_request') }}">Reset</a>      
    </div>
{% endblock main %}

gravity/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block main%}
    <div class="container">
        <div class="row mb-5">
            <h2>Usage</h2>
            <p> Login to your account in order to use the full scope of the website. </p>
            <p> To add a satellite, fill in the form on the right side of the page with the following information:
                Name, Initial position (in km), Initial velocity (in km/s). 
                Make sure to enter the position and velocity in the correct units. </p>
            <p> To view the table of satellites you have added, look at the table in the main section of the page. The table will show the name, initial position, and initial velocity of each satellite.
                To generate a plot of all your satellites, enter the view angle (in degrees, both horizontal and vertical separated by a comma) in the form on the right side of the page and submit it. The plot will be displayed in the main section of the page.
                To delete a satellite, locate it in the table and click the "Delete" button next to it. </p>
            <p> Examples of reasonable values for satellites orbiting Earth include geostationary orbit (pos: 42164, 0, 0; vel: 0, 3.07, 0) and International Space Station orbit (pos: 6779, -3418, 4307; vel: 7.66, 0, 7.66)</p>            
        </div>
        <div class="row">
            <div class="col-sm-9">
                <!-- Plot -->
                <div class="row d-flex justify-content-center">
                    <img class="plot-image px-5" src="{{ plot_image }}">
                </div>
                <!-- Table with satelites owned by user -->
                {% if current_user.is_authenticated %}
                    <div class="row">
                        <div class="row my-5">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Initial position [km]</th>
                                            <th>Initial velocity [km/s]</th>
                                            <th>Delete</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for row in user_satelites %}
                                            <tr>
                                                <td>{{ row.name }}</td>
                                                <td>{{ row.pos_0 }}</td>
                                                <td>{{ row.vel_0 }}</td>
                                                <td>
                                                    <form action="{{ url_for('main.delete_satelite', satelite_id=row.id) }}" method="POST">
                                                        <input class="btn btn-delete btn-sm" type="submit" value="Delete">
                                                    </form> 
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div> 
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-sm-3">
                <!-- Form to add satelites -->
                <form method="POST" action="">
                    <!-- Security related -->
                    {{ form.hidden_tag() }}
            
                    <fieldset class="form-group">
                        <legend class="border-bottom border-dark mb-4">Add Satelite</legend>
                        <div class="form-group">
                            {{ form.name.label(class="form-control-label") }}
                            <!-- Handle messages to users about wrong information -->
                            {% if form.name.errors %}
                                {{ form.name(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.name.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.name(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.pos.label(class="form-control-label") }}
                            <!-- Handle messages to users about wrong information -->
                            {% if form.pos.errors %}
                                {{ form.pos(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.pos.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.pos(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.vel.label(class="form-control-label") }}
                            <!-- Handle messages to users about wrong information -->
                            {% if form.vel.errors %}
                                {{ form.vel(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.vel.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.vel(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
                <!-- Form plot all satelites -->
                {% if current_user.is_authenticated %}
                    <form method="POST" action="">
                        <!-- Security related -->
                        {{ plot_form.hidden_tag() }}
                
                        <fieldset class="form-group">
                            <legend class="border-bottom border-dark mb-4">Generate Plot</legend>
                            <div class="form-group">
                                {{ plot_form.view_angles.label(class="form-control-label") }}
                                <!-- Handle messages to users about wrong information -->
                                {% if plot_form.view_angles.errors %}
                                    {{ plot_form.view_angles(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in plot_form.view_angles.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ plot_form.view_angles(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="form-group">
                            {{ plot_form.submit(class="btn btn-outline-info") }}
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>    
{% endblock main %}

gravity/templates/index.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block main%}
    <h1>
        Home page!
    </h1>
{% endblock main %}

gravity/templates/layout.html
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
        <!-- My CSS -->
        <link rel="stylesheet" href="/static/gravity.css">

        <!-- Favicon -->
        <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/static/favicon.ico" type="image/x-icon">

        <!-- Page Title -->
        <title>Gravity: {% block title %}{% endblock %}</title>
    </head>

    <body>
        <!-- Navigation bar -->
        <header class="site-header">
            <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
                <div class="container">
                    <a class="navbar-brand" href="{{ url_for('main.home') }}">
                        <img src="/static/favicon.ico" alt="" width="24" height="24" class="d-inline-block align-text-top">
                        Gravity
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="mynavbar">
                        <div class="container-fluid d-flex justify-content-between">
                            <!-- Left side links -->
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                                </li>
                            </ul>
                            <!-- Right side links -->
                            <ul class="navbar-nav">
                                {% if current_user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('users.account') }}">
                                            <img src="/static/profile_pictures/{{ current_user.image_file }}" alt="" width="24" height="24" class="rounded-circle d-inline-block align-text-top border border-secondary mx-1">
                                            Account
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Change active link by activePage script -->
            <script src="/static/activePage.js"></script>
        </header>


        <main class="container py-5 justify-content-sm-center">
            <!-- Flash messages -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <header>
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </header>
                {% endif %}
            {% endwith%}
            <!-- Main content -->
            {% block main %}{% endblock %}
        </main>


    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>

</html>

gravity/templates/login.html
{% extends "layout.html" %}

{% block title %}
    Login
{% endblock title %}

{% block main%}
    <form method="POST" action="">
        <!-- Security related -->
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom border-dark mb-4">Log In</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted px-2">
                <a class="ml-2" href="{{ url_for('users.password_reset_request') }}">Forgot Password?</a>      
            </small>
        </div>
    </form>
    <div class="border-top border-dark pt-3">
        <small class="text-muted">
            New To Our Service? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>      
        </small>
    </div>
{% endblock main %}

gravity/templates/password_reset.html
{% extends "layout.html" %}

{% block title %}
    Password Reset
{% endblock title %}

{% block main%}
    <form method="POST" action="">
        <!-- Security related -->
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom border-dark mb-4">Request Password Reset</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
{% endblock main %}

gravity/templates/password_reset_token.html
{% extends "layout.html" %}

{% block title %}
    Reset Password
{% endblock title %}

{% block main%}
    <form method="POST" action="">
        <!-- Security related -->
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom border-dark mb-4">Choose New Password</legend>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password_confirm.label(class="form-control-label") }}
                <!-- Handle messages to users about wrong information -->
                {% if form.password_confirm.errors %}
                    {{ form.password_confirm(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password_confirm.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password_confirm(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
{% endblock main %}